UserIdentity/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UserIdentity.Models;

namespace UserIdentity.Controllers
{
    public class StaffsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize(Roles = "Staff, Admin")]
        // GET: Staffs
        public ActionResult Index()
        {
            return View(db.Staffs.ToList());
        }
        

        // GET: Staffs/Details/5
        [Authorize(Roles = "Staff, Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staffs/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StaffID,Name,DateOfBirth,Gender,PhoneNumber,Email,City")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Staffs.Add(staff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(staff);
        }

        // GET: Staffs/Edit/5
        [Authorize(Roles = "Staff, Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StaffID,Name,DateOfBirth,Gender,PhoneNumber,Email,City")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(staff);
        }

        // GET: Staffs/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Staff staff = db.Staffs.Find(id);
            db.Staffs.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UserIdentity/Controllers/TermsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UserIdentity.Models;

namespace UserIdentity.Controllers
{
    public class TermsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

       
        [Authorize(Roles = "Staff, Trainer, Trainee")]
        public ActionResult Index()
        {
            return View(db.Terms.ToList());
        }

       
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Term term = db.Terms.Find(id);
            if (term == null)
            {
                return HttpNotFound();
            }
            return View(term);
        }
 
        [Authorize(Roles = "Staff")]
        public ActionResult Create()
        {
            return View();
        }

   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TermID,TermName,DayStart,DayFinish")] Term term)
        {
            if (ModelState.IsValid)
            {
                db.Terms.Add(term);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(term);
        }

      
        [Authorize(Roles = "Staff")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Term term = db.Terms.Find(id);
            if (term == null)
            {
                return HttpNotFound();
            }
            return View(term);
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TermID,TermName,DayStart,DayFinish")] Term term)
        {
            if (ModelState.IsValid)
            {
                db.Entry(term).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(term);
        }

     
        [Authorize(Roles = "Staff")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Term term = db.Terms.Find(id);
            if (term == null)
            {
                return HttpNotFound();
            }
            return View(term);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Term term = db.Terms.Find(id);
            db.Terms.Remove(term);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UserIdentity/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UserIdentity.Models;

namespace UserIdentity.Controllers
{
    public class TopicsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

      
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Topics.ToList());
        }
     
        [Authorize(Roles = "Staff, Trainee, Trainer")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

    
        [Authorize(Roles = "Staff")]
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TopicID,TopicName,TopicDescription")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Topics.Add(topic);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(topic);
        }

      
        [Authorize(Roles = "Staff")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TopicID,TopicName,TopicDescription")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(topic);
        }

      
        [Authorize(Roles = "Staff")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

   
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Topic topic = db.Topics.Find(id);
            db.Topics.Remove(topic);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UserIdentity/Views/Shared/_AdminMenu.cshtml
<!DOCTYPE html>
<html>
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
<body>

    <div id="wrapper">
        <div class="overlay">
        </div>
        <ul class="nav sidebar-nav">
            <li class="sidebar-brand">
                @Html.ActionLink("FPT-NST-CM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </li>
            <li>@Html.ActionLink("Manage Staffs", "Index", "Staffs")</li>
            <li>@Html.ActionLink("Manage Trainers", "Index", "Trainers")</li>
            <li>@Html.ActionLink("Manage Account", "_ExternalLoginsListPartial", "Account")</li>
            <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        </ul>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

UserIdentity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FPT-Managerment Course System </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
                 @Html.Partial("_Login")
                 @Html.Partial("_LoginPartial")
              
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - FPT-Managerment Course System</p>
            </footer>
        </div>
        

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

UserIdentity/Views/Shared/_Login.cshtml
@{
    ViewBag.Title = "_Login";
}



@if (Request.IsAuthenticated)
{
    if (User.IsInRole("Trainer"))
    {
        @Html.Partial("_TrainerMenu");
    }
    else if (User.IsInRole("Staff"))
    {
        @Html.Partial("_StaffMenu");
    }
    else if (User.IsInRole("Admin"))
    {
        @Html.Partial("_AdminMenu");
    }
    else if (User.IsInRole("Trainee"))
    {
        @Html.Partial("_TraineeMenu");
    }
}

UserIdentity/Views/Shared/_StaffMenu.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div id="wrapper">
        <div class="overlay">
        </div>
        <ul class="nav sidebar-nav">
            <li class="sidebar-brand">
                @Html.ActionLink("FPT-NST-CM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </li>
            <li>@Html.ActionLink("Manage Trainees", "Index", "Trainees")</li>
            <li>@Html.ActionLink("Manage Trainers", "Index", "Trainers")</li>
            <li>@Html.ActionLink("Manage Topics", "Index", "Topics")</li>
            <li>@Html.ActionLink("Manage Terms", "Index", "Terms")</li>
            <li>@Html.ActionLink("Manage Couses", "Index", "Courses")</li>
            <li>@Html.ActionLink("Manage Sessions", "Index", "Sessions")</li>
            <li>@Html.ActionLink("Manage Trainer Asigns", "Index", "TrainerAsigns")</li>
            <li>@Html.ActionLink("Manage Trainee Asigns", "Index", "TraineeAsigns")</li>
            <li>@Html.ActionLink("Infomation", "Index", "Staffs")</li>
        </ul>
       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

UserIdentity/Views/Shared/_TraineeMenu.cshtml
<!DOCTYPE html>
<html>
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
<body>
    <div id="wrapper">
        <div class="overlay">
        </div>
        <ul class="nav sidebar-nav">
            <li class="sidebar-brand">
                @Html.ActionLink("FPT-NST-CM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </li>
            <li>@Html.ActionLink("Manage information", "Edit", "Trainees")</li>
            <li>@Html.ActionLink("See All Courses", "Index", "Courses")</li>
            <li>@Html.ActionLink("See All Topics", "Index", "Topics")</li>
            <li>@Html.ActionLink("Terms", "Index", "Terms")</li>
            <li>@Html.ActionLink("My Courses", "Index", "TraineeAsigns")</li>
        </ul>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

UserIdentity/Views/Shared/_TrainerMenu.cshtml
<!DOCTYPE html>
<html>
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
<body>
    <div id="wrapper">
        <div class="overlay">
        </div>
        <ul class="nav sidebar-nav">
            <li class="sidebar-brand">
                @Html.ActionLink("FPT-NST-CM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </li>
            <li>@Html.ActionLink("Manage information", "Details", "Trainers")</li>
            <li>@Html.ActionLink("See All Courses", "Index", "Courses")</li>
            <li>@Html.ActionLink("See All Topics", "Index", "Topics")</li>
            <li>@Html.ActionLink("Terms", "Index", "Terms")</li>
            <li>@Html.ActionLink("My Courses", "Index", "TrainerAsigns")</li>
        </ul>

    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
   
</body>
</html>